apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: py
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: py
    spec:
      containers:
      - name: py
        image: vjaishankarsai/pyimage:first
        command: ["tail", "-f", "/dev/null"]
        ports:
        - containerPort: 85
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
